In [1]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Reading dataset

dataset=pd.read_csv("housing_prices_MLR.csv")
dataset

    AREA  FLOOR  ROOM CODE  PRICE
0   1000      7     2    B   5618
1   1030      7     1    A   5201
2   1060      1     1    A   4779
3   1090      6     1    A   5425
4   1120      0     2    B   5657
5   1150      1     1    B   4945
6   1180      6     2    B   6475
7   1210      0     1    A   5352
8   1240      0     2    B   6290
9   1270      7     1    A   6147
10  1300     10     2    A   7718
11  1330      3     2    B   7035
12  1360      3     3    B   8712
13  1390      8     3    B   9457
14  1420      3     2    A   7304
15  1450      7     2    B   7535
16  1480      8     3    B   9968
17  1510      7     2    A   7614
18  1540      6     3    A   9762
19  1570      8     3    A  10067
20  1600      6     2    A   8074
21  1630      4     3    B  10201
22  1660      1     3    B  10051
23  1690      3     3    B   9775
24  1720      3     3    A  10229
25  1750      0     2    A   8314
26  1780      4     2    A   9288
27  1810      1     3    B  10503
28  1840      6     2    A   9763
29  1870      6     3    A  11527
30  1900      8     2    B   9912
31  1930      8     2    B  10204
32  1960      0     2    B   9085
33  1990      8     2    A  10240
34  2020      0     4    B  15220
35  2050     10     3    A  12278
36  2080      9     5    A  22270
37  2110     10     3    A  12574
38  2140      7     3    B  12618
39  2170      1     4    B  15457
40  2200      4     3    A  12793
41  2230      3     3    B  12641
42  2260      8     4    A  17207
43  2290      4     4    B  16969
44  2320      2     4    B  16293
45  2350      5     4    B  16845
46  2380     10     4    B  17604
47  2410      6     4    B  17310
48  2440      9     3    B  14036
49  2470      3     3    B  13699

In [3]:
# separation of features and target and converting into arrays

x=dataset.iloc[:,:4].values
y=dataset.iloc[:,-1].values

In [4]:
# Encoding Categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_x=LabelEncoder()
x[:,3]=labelencoder_x.fit_transform(x[:,3])
onehotencoder=OneHotEncoder(categorical_features=[3])
x=onehotencoder.fit_transform(x).toarray()
x

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

array([[0.00e+00, 1.00e+00, 1.00e+03, 7.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.03e+03, 7.00e+00, 1.00e+00],
       [1.00e+00, 0.00e+00, 1.06e+03, 1.00e+00, 1.00e+00],
       [1.00e+00, 0.00e+00, 1.09e+03, 6.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.12e+03, 0.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.15e+03, 1.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.18e+03, 6.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.21e+03, 0.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.24e+03, 0.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.27e+03, 7.00e+00, 1.00e+00],
       [1.00e+00, 0.00e+00, 1.30e+03, 1.00e+01, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.33e+03, 3.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.36e+03, 3.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.39e+03, 8.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.42e+03, 3.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.45e+03, 7.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.48e+03, 8.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.51e+03, 7.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.54e+03, 6.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.57e+03, 8.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.60e+03, 6.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.63e+03, 4.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.66e+03, 1.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.69e+03, 3.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.72e+03, 3.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.75e+03, 0.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.78e+03, 4.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.81e+03, 1.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.84e+03, 6.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.87e+03, 6.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.90e+03, 8.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.93e+03, 8.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.96e+03, 0.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.99e+03, 8.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 2.02e+03, 0.00e+00, 4.00e+00],
       [1.00e+00, 0.00e+00, 2.05e+03, 1.00e+01, 3.00e+00],
       [1.00e+00, 0.00e+00, 2.08e+03, 9.00e+00, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.11e+03, 1.00e+01, 3.00e+00],
       [0.00e+00, 1.00e+00, 2.14e+03, 7.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 2.17e+03, 1.00e+00, 4.00e+00],
       [1.00e+00, 0.00e+00, 2.20e+03, 4.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 2.23e+03, 3.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 2.26e+03, 8.00e+00, 4.00e+00],
       [0.00e+00, 1.00e+00, 2.29e+03, 4.00e+00, 4.00e+00],
       [0.00e+00, 1.00e+00, 2.32e+03, 2.00e+00, 4.00e+00],
       [0.00e+00, 1.00e+00, 2.35e+03, 5.00e+00, 4.00e+00],
       [0.00e+00, 1.00e+00, 2.38e+03, 1.00e+01, 4.00e+00],
       [0.00e+00, 1.00e+00, 2.41e+03, 6.00e+00, 4.00e+00],
       [0.00e+00, 1.00e+00, 2.44e+03, 9.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 2.47e+03, 3.00e+00, 3.00e+00]])

In [5]:
#Training the algorithm
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)
x_train

array([[0.00e+00, 1.00e+00, 1.36e+03, 3.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.12e+03, 0.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 2.11e+03, 1.00e+01, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.24e+03, 0.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.09e+03, 6.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.18e+03, 6.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 2.23e+03, 3.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 2.38e+03, 1.00e+01, 4.00e+00],
       [0.00e+00, 1.00e+00, 2.41e+03, 6.00e+00, 4.00e+00],
       [0.00e+00, 1.00e+00, 1.45e+03, 7.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.27e+03, 7.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.48e+03, 8.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.72e+03, 3.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 2.02e+03, 0.00e+00, 4.00e+00],
       [0.00e+00, 1.00e+00, 1.93e+03, 8.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.00e+03, 7.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 2.32e+03, 2.00e+00, 4.00e+00],
       [0.00e+00, 1.00e+00, 1.81e+03, 1.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.99e+03, 8.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.15e+03, 1.00e+00, 1.00e+00],
       [1.00e+00, 0.00e+00, 1.87e+03, 6.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.33e+03, 3.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 2.08e+03, 9.00e+00, 5.00e+00],
       [1.00e+00, 0.00e+00, 1.03e+03, 7.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.63e+03, 4.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.06e+03, 1.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 2.29e+03, 4.00e+00, 4.00e+00],
       [1.00e+00, 0.00e+00, 2.05e+03, 1.00e+01, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.69e+03, 3.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 2.20e+03, 4.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.30e+03, 1.00e+01, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.66e+03, 1.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.54e+03, 6.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 2.47e+03, 3.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.60e+03, 6.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.21e+03, 0.00e+00, 1.00e+00],
       [1.00e+00, 0.00e+00, 2.26e+03, 8.00e+00, 4.00e+00],
       [1.00e+00, 0.00e+00, 1.42e+03, 3.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.84e+03, 6.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 2.14e+03, 7.00e+00, 3.00e+00]])

In [6]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

y_pred = reg.predict(x_train)

In [7]:
reg.score(x_train,y_train)

0.9461457392086272

In [8]:
reg.score(x_test,y_test)

0.9461868328933407